---
- name: copying ssh key and updating sudoers
  hosts: '{{ host }}'
  gather_facts: false
  remote_user: root
  become: yes

  tasks:
    
    - name: Add Entry to the Known Hosts
      shell: ssh-keyscan '{{ host }}' >> ~/.ssh/known_hosts
     
#    - name: Copy SSh Key | copying shh key to remote host
#      authorized_key:
#        user: root
#        state: present
#        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
    
    - name: "Creating Oinstall and DBA Groups"
      group:
        name: "{{ item }}"
        state: present
      loop:
        - oinstall
        - dba
   
    - name: " Creating Oracle User"
      user:
        name: oracle
        shell: /bin/bash
        groups: oinstall,dba
        append: yes
  
    - name: "Print Username"
      shell: whoami
      register: user

    - name: "Debug User name"
      debug:
        var: user
