---
#- name: copying ssh key and updating sudoers
#  hosts: '{{ host }}'
#  gather_facts: false
#  remote_user: root
#  become: yes

#  tasks:
    
    - name: Add Entry to the Known Hosts
      shell: ssh-keyscan '{{ host }}' >> ~/.ssh/known_hosts
     
#    - name: Copy SSh Key | copying shh key to remote host
#      authorized_key:
#        user: root
#        state: present
#        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
    
    - name: "Getting Host name (1/4)"
      shell: hostname
      register: hostname
   
    - name: "Listing Network Interfaces (2/4)"
      shell: ip addr show | grep '^[0-9]' | awk '{print $2}' | sed 's/://' | grep ens*
      register: interface_result
 
    - name: "Get IP Addresses(3/4)"
      shell: "ip addr show {{ item }} | grep 'inet ' | awk '{print $2}'"
      register: ip_result
      loop: "{{ interface_result.stdout_lines }}"
     
    - name: "Updating Hosts File (4/4)"
      lineinfile:
        path: "/etc/hosts"
        line: "{{ ip_result.results[0].stdout[:-3] }}  {{ hostname.stdout }}.localdomain  {{ hostname.stdout }}"   

    - name: "Creating Oinstall and DBA Groups"
      group:
        name: "{{ item }}"
        state: present
      loop:
        - oinstall
        - dba
   
    - name: " Creating Oracle User"
      user:
        name: oracle
        shell: /bin/bash
        groups: oinstall,dba
        append: yes
    
    - name: "Adding oracle to Oinstall as primary"
      shell: "{{ item }}"
      loop:
        - usermod -g oinstall oracle
        - usermod -a -G dba oracle
  
    - name: "Print Username"
      shell: whoami
      register: user
    
    - name: "Install RPMs"
      include_tasks:
        file: rpm_install.yml

    - name: "Creating Directories"
      include_tasks:
        file: creating_Directory.yml
   
    - name: Adding Kernal Parameters
      blockinfile:
        path: /etc/sysctl.conf
        backup: no
        block: |
          fs.aio-max-nr = 1048576
          fs.file-max = 6815744
          kernel.shmall = 2097152
          kernel.shmmax = 8329226240
          kernel.shmmni = 4096
          kernel.sem = 250 32000 100 128
          net.ipv4.ip_local_port_range = 9000 65500
          net.core.rmem_default = 262144
          net.core.rmem_max = 4194304
          net.core.wmem_default = 262144
          net.core.wmem_max = 1048586
  
    - name: Adding  limits for oracle
      blockinfile:
        path: /etc/security/limits.conf
        backup: no
        block: |
          oracle soft nproc 2047
          oracle hard nproc 16384
          oracle soft nofile 1024
          oracle hard nofile 65536
   
    - name: "Executing Kernal Parameters"
      shell: sysctl -p
